#! /bin/bash
### BEGIN INIT INFO
# Provides:          phpdaemon
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop the phpdaemon server.
# Description:       Test phpdaemon server.
### END INIT INFOR

NAME=phpdaemon
DESC="PHP daemon server"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"
SCRIPTNAME=/etc/init.d/$NAME

DAEMON="/usr/bin/php"
DAEMON_OPTS="/home/andy/www/react/server.php"

START_OPTS="--start --oknodo --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} ${DAEMON_OPTS}"
STOP_OPTS="--stop  --oknodo --pidfile ${PIDFILE}"

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" $NAME
        if start-stop-daemon $START_OPTS
        then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" $NAME
        if start-stop-daemon $STOP_OPTS
        then
            rm -f $PIDFILE
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        status_of_proc -p "$PIDFILE" "$DAEMON" phpdaemon && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
